.TH "crypto" 3 "Mon Oct 3 2022" "Version 1.2" "TiigerTLS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crypto \- crypto context structure  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tls1_3\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBactive\fP"
.br
.ti -1c
.RI "char \fBk\fP [\fBTLS_MAX_KEY\fP]"
.br
.ti -1c
.RI "char \fBiv\fP [12]"
.br
.ti -1c
.RI "\fBoctad\fP \fBK\fP"
.br
.ti -1c
.RI "\fBoctad\fP \fBIV\fP"
.br
.ti -1c
.RI "\fBunsign32\fP \fBrecord\fP"
.br
.ti -1c
.RI "int \fBsuite\fP"
.br
.ti -1c
.RI "int \fBtaglen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
crypto context structure 
.SH "Member Data Documentation"
.PP 
.SS "bool crypto::active"
Indicates if encryption has been activated 
.SS "char crypto::iv[12]"
AEAD cryptographic IV bytes 
.SS "\fBoctad\fP crypto::IV"
IV as octad 
.SS "char crypto::k[\fBTLS_MAX_KEY\fP]"
AEAD cryptographic Key bytes 
.SS "\fBoctad\fP crypto::K"
Key as octad 
.SS "\fBunsign32\fP crypto::record"
current record number - to be incremented 
.SS "int crypto::suite"
Cipher Suite 
.SS "int crypto::taglen"
Tag Length 

.SH "Author"
.PP 
Generated automatically by Doxygen for TiigerTLS from the source code\&.
