.TH "ee_status" 3 "Mon Oct 3 2022" "Version 1.2" "TiigerTLS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ee_status \- server encrypted extensions expectations/responses  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tls1_3\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBearly_data\fP"
.br
.ti -1c
.RI "bool \fBalpn\fP"
.br
.ti -1c
.RI "bool \fBserver_name\fP"
.br
.ti -1c
.RI "bool \fBmax_frag_length\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
server encrypted extensions expectations/responses 
.SH "Member Data Documentation"
.PP 
.SS "bool ee_status::alpn"
true if ALPN accepted 
.SS "bool ee_status::early_data"
true if early data accepted 
.SS "bool ee_status::max_frag_length"
true if max frag length respected 
.SS "bool ee_status::server_name"
true if server name accepted 

.SH "Author"
.PP 
Generated automatically by Doxygen for TiigerTLS from the source code\&.
