.TH "md_blogs__r_e_a_d_m_e" 3 "Mon Oct 3 2022" "Version 1.2" "TiigerTLS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_blogs__r_e_a_d_m_e \- Blogs 
.PP
These blogs are the completely unfiltered thoughts that passed through the developers head while developing this software\&. In hindsight much of the commentary turned out to be wrong, misplaced, ill-informed\&. It may help explain some of the design decisions\&. 
