.TH "octad" 3 "Mon Oct 3 2022" "Version 1.2" "TiigerTLS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
octad \- Safe representation of an octad\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tls_octads\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBlen\fP"
.br
.ti -1c
.RI "int \fBmax\fP"
.br
.ti -1c
.RI "char * \fBval\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Safe representation of an octad\&. 
.SH "Member Data Documentation"
.PP 
.SS "int octad::len"
length in bytes 
.br
 
.SS "int octad::max"
max length allowed - enforce truncation 
.SS "char* octad::val"
byte array 
.br
 

.SH "Author"
.PP 
Generated automatically by Doxygen for TiigerTLS from the source code\&.
