.TH "pktype" 3 "Mon Oct 3 2022" "Version 1.2" "TiigerTLS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pktype \- Public key type\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tls_x509\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "int \fBhash\fP"
.br
.ti -1c
.RI "int \fBcurve\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Public key type\&. 
.SH "Member Data Documentation"
.PP 
.SS "int pktype::curve"
elliptic curve used or RSA key length in bits 
.br
 
.SS "int pktype::hash"
hash type 
.SS "int pktype::type"
signature type (ECC or RSA) 

.SH "Author"
.PP 
Generated automatically by Doxygen for TiigerTLS from the source code\&.
