.TH "Socket" 3 "Mon Oct 3 2022" "Version 1.2" "TiigerTLS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Socket \- \fBSocket\fP instance\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tls_sockets\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBconnect\fP (char *host, int port)"
.br
.ti -1c
.RI "void \fBsetTimeout\fP (int to)"
.br
.ti -1c
.RI "int \fBwrite\fP (char *buf, int len)"
.br
.ti -1c
.RI "int \fBread\fP (char *buf, int len)"
.br
.ti -1c
.RI "void \fBstop\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSocket\fP \fBInetSocket\fP ()"
.br
.ti -1c
.RI "static \fBSocket\fP \fBUnixSocket\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBSocket\fP instance\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for TiigerTLS from the source code\&.
