.TH "ticket" 3 "Mon Oct 3 2022" "Version 1.2" "TiigerTLS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ticket \- ticket context structure  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tls1_3\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBvalid\fP"
.br
.ti -1c
.RI "char \fBtick\fP [\fBTLS_MAX_TICKET_SIZE\fP]"
.br
.ti -1c
.RI "char \fBnonce\fP [256]"
.br
.ti -1c
.RI "char \fBpsk\fP [\fBTLS_MAX_HASH\fP]"
.br
.ti -1c
.RI "\fBoctad\fP \fBTICK\fP"
.br
.ti -1c
.RI "\fBoctad\fP \fBNONCE\fP"
.br
.ti -1c
.RI "\fBoctad\fP \fBPSK\fP"
.br
.ti -1c
.RI "\fBunsign32\fP \fBage_obfuscator\fP"
.br
.ti -1c
.RI "\fBunsign32\fP \fBmax_early_data\fP"
.br
.ti -1c
.RI "\fBunsign32\fP \fBbirth\fP"
.br
.ti -1c
.RI "int \fBlifetime\fP"
.br
.ti -1c
.RI "int \fBcipher_suite\fP"
.br
.ti -1c
.RI "int \fBfavourite_group\fP"
.br
.ti -1c
.RI "int \fBorigin\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
ticket context structure 
.SH "Member Data Documentation"
.PP 
.SS "\fBunsign32\fP ticket::age_obfuscator"
ticket age obfuscator - 0 for external PSK 
.SS "\fBunsign32\fP ticket::birth"
Birth time of this ticket 
.SS "int ticket::cipher_suite"
Cipher suite used 
.SS "int ticket::favourite_group"
the server's favourite group 
.SS "int ticket::lifetime"
ticket lifetime 
.SS "\fBunsign32\fP ticket::max_early_data"
Maximum early data allowed for this ticket 
.SS "char ticket::nonce[256]"
nonce 
.SS "\fBoctad\fP ticket::NONCE"
Nonce as octad 
.SS "int ticket::origin"
Origin of initial handshake - Full or PSK? 
.SS "char ticket::psk[\fBTLS_MAX_HASH\fP]"
pre-shared key 
.SS "\fBoctad\fP ticket::PSK"
PSK as octad 
.SS "char ticket::tick[\fBTLS_MAX_TICKET_SIZE\fP]"
Ticket bytes 
.SS "\fBoctad\fP ticket::TICK"
Ticket or external PSK label as octad 
.SS "bool ticket::valid"
Is ticket valid? 

.SH "Author"
.PP 
Generated automatically by Doxygen for TiigerTLS from the source code\&.
