.TH "C:/Users/mscot/TLS1.3/cpp/include/tls_wifi.h" 3 "Mon Oct 3 2022" "Version 1.2" "TiigerTLS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/mscot/TLS1.3/cpp/include/tls_wifi.h \- define \fBSocket\fP structure depending on processor context  

.SH SYNOPSIS
.br
.PP
\fC#include 'tls1_3\&.h'\fP
.br

.SH "Detailed Description"
.PP 
define \fBSocket\fP structure depending on processor context 


.PP
\fBAuthor\fP
.RS 4
Mike Scott  
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TiigerTLS from the source code\&.
