.TH "C:/Users/mscot/TLS1.3/cpp/include/tls_cert_chain.h" 3 "Mon Oct 3 2022" "Version 1.2" "TiigerTLS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/mscot/TLS1.3/cpp/include/tls_cert_chain.h \- Process Certificate Chain\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'tls1_3\&.h'\fP
.br
\fC#include 'tls_x509\&.h'\fP
.br
\fC#include 'tls_sal\&.h'\fP
.br
\fC#include 'tls_client_recv\&.h'\fP
.br
\fC#include 'tls_logger\&.h'\fP
.br
\fC#include 'tls_certs\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcheckServerCertChain\fP (\fBoctad\fP *CERTCHAIN, char *hostname, \fBoctad\fP *PUBKEY, \fBoctad\fP *SIG)"
.br
.RI "Check Certificate Chain for hostname, and extract public key\&. "
.ti -1c
.RI "int \fBgetClientPrivateKeyandCertChain\fP (int nccsalgs, int *csigAlgs, \fBoctad\fP *PRIVKEY, \fBoctad\fP *CERTCHAIN)"
.br
.RI "Get Client private key and Certificate chain from \&.pem files\&. "
.in -1c
.SH "Detailed Description"
.PP 
Process Certificate Chain\&. 


.PP
\fBAuthor\fP
.RS 4
Mike Scott  
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int checkServerCertChain (\fBoctad\fP * CERTCHAIN, char * hostname, \fBoctad\fP * PUBKEY, \fBoctad\fP * SIG)"

.PP
Check Certificate Chain for hostname, and extract public key\&. 
.PP
\fBParameters\fP
.RS 4
\fICERTCHAIN\fP the input certificate chain 
.br
\fIhostname\fP the input Server name associated with the Certificate chain 
.br
\fIPUBKEY\fP the Server's public key extracted from the Certificate chain 
.br
\fISIG\fP signature (supplied as workspace) 
.RE
.PP
\fBReturns\fP
.RS 4
0 if certificate chain is OK, else returns negative failure reason 
.RE
.PP

.SS "int getClientPrivateKeyandCertChain (int nccsalgs, int * csigAlgs, \fBoctad\fP * PRIVKEY, \fBoctad\fP * CERTCHAIN)"

.PP
Get Client private key and Certificate chain from \&.pem files\&. 
.PP
\fBParameters\fP
.RS 4
\fInccsalgs\fP the number of acceptable signature algorithms 
.br
\fIcsigAlgs\fP acceptable signature algorithms 
.br
\fIPRIVKEY\fP the Client's private key 
.br
\fICERTCHAIN\fP the Client's certificate chain 
.RE
.PP
\fBReturns\fP
.RS 4
type of private key, ECC or RSA 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TiigerTLS from the source code\&.
