.TH "C:/Users/mscot/TLS1.3/cpp/include/tls_tickets.h" 3 "Mon Oct 3 2022" "Version 1.2" "TiigerTLS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/mscot/TLS1.3/cpp/include/tls_tickets.h \- TLS 1\&.3 process resumption tickets\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'tls1_3\&.h'\fP
.br
\fC#include 'tls_client_recv\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "unsigned long \fBmillis\fP ()"
.br
.RI "read milliseconds from a stop-watch "
.ti -1c
.RI "int \fBparseTicket\fP (\fBoctad\fP *TICK, \fBunsign32\fP birth, \fBticket\fP *T)"
.br
.RI "parse a received ticket octad into a ticket structure "
.ti -1c
.RI "void \fBinitTicketContext\fP (\fBticket\fP *T)"
.br
.RI "initialize a ticket structure "
.ti -1c
.RI "void \fBendTicketContext\fP (\fBticket\fP *T)"
.br
.RI "terminate a ticket structure "
.ti -1c
.RI "bool \fBticket_still_good\fP (\fBticket\fP *T)"
.br
.RI "Check that a ticket is still good, and not out-of-date\&. "
.in -1c
.SH "Detailed Description"
.PP 
TLS 1\&.3 process resumption tickets\&. 


.PP
\fBAuthor\fP
.RS 4
Mike Scott  
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void endTicketContext (\fBticket\fP * T)"

.PP
terminate a ticket structure 
.PP
\fBParameters\fP
.RS 4
\fIT\fP the ticket structure 
.RE
.PP

.SS "void initTicketContext (\fBticket\fP * T)"

.PP
initialize a ticket structure 
.PP
\fBParameters\fP
.RS 4
\fIT\fP the ticket structure 
.RE
.PP

.SS "unsigned long millis ()"

.PP
read milliseconds from a stop-watch 
.PP
\fBReturns\fP
.RS 4
milliseconds read from stop-watch 
.RE
.PP

.SS "int parseTicket (\fBoctad\fP * TICK, \fBunsign32\fP birth, \fBticket\fP * T)"

.PP
parse a received ticket octad into a ticket structure 
.PP
\fBParameters\fP
.RS 4
\fITICK\fP the input ticket octad 
.br
\fIT\fP the output ticket structure 
.br
\fIbirth\fP the birth time of the ticket 
.RE
.PP
\fBReturns\fP
.RS 4
bad ticket error, or 0 if ticket is good 
.RE
.PP

.SS "bool ticket_still_good (\fBticket\fP * T)"

.PP
Check that a ticket is still good, and not out-of-date\&. 
.PP
\fBParameters\fP
.RS 4
\fIT\fP the ticket structure 
.RE
.PP
\fBReturns\fP
.RS 4
true if ticket is still good 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TiigerTLS from the source code\&.
