.TH "unihash" 3 "Mon Oct 3 2022" "Version 1.2" "TiigerTLS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
unihash \- Universal Hash Function\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tls1_3\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBstate\fP [\fBTLS_MAX_HASH_STATE\fP]"
.br
.ti -1c
.RI "int \fBhtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Universal Hash Function\&. 
.SH "Member Data Documentation"
.PP 
.SS "int unihash::htype"
The hash type (typically SHA256) 
.SS "char unihash::state[\fBTLS_MAX_HASH_STATE\fP]"
hash function state 

.SH "Author"
.PP 
Generated automatically by Doxygen for TiigerTLS from the source code\&.
