[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mcore = { path = "../../rust/mcore" }
getrandom = "0.2.5"
base64 = "0.13.0"
